#include<bits/stdc++.h>
#define ll long long
using namespace std;
int main()
{
    ll a,b,x,c=0,d,e;
    cin>>a>>b>>x;
    if(a>=b)
    {
        cout<<"0";
        a--;
        while(1)
        {

            if(x==1)
            {
                if(c==0)
                {
                    while(1)
                    {
                        if(a==0)
                            break;
                        else
                        {
                            cout<<"0";
                            a--;
                        }
                    }
                    while(1)
                    {
                        if(b==0)
                            break;
                        else
                        {
                            cout<<"1";
                            b--;
                        }
                    }
                }
                else
                {
                    {
                        while(1)
                        {
                            if(b==0)
                                break;
                            else
                            {
                                cout<<"1";
                                b--;
                            }
                        }
                    }

                    while(1)
                    {
                        if(a==0)
                            break;
                        else
                        {
                            cout<<"0";
                            a--;
                        }
                    }
                }
                break;
            }
            else
            {
                if(c==0)
                {
                    cout<<"1";
                    b--;
                    x--;
                    c=1;
                }
                else
                {
                    cout<<"0";
                    a--;
                    x--;
                    c=0;
                }
            }
            //cout<<endl<<x<<endl;
        }
    }
    else
    {
        cout<<"1";
        b--;
        while(1)
        {
            if(x==1)
            {
                if(c==0)
                {
                    while(1)
                    {
                        if(b==0)
                            break;
                        else
                        {
                            cout<<"1";
                            b--;
                        }
                    }
                    while(1)
                    {
                        if(a==0)
                            break;
                        else
                        {
                            cout<<"0";
                            a--;
                        }
                    }
                }
                else
                {
                    {
                        while(1)
                        {
                            if(a==0)
                                break;
                            else
                            {
                                cout<<"0";
                                a--;
                            }
                        }
                    }

                    while(1)
                    {
                        if(b==0)
                            break;
                        else
                        {
                            cout<<"1";
                            b--;
                        }
                    }
                }
                break;
            }
            else
            {
                if(c==0)
                {
                    cout<<"0";
                    a--;
                    x--;
                    c=1;
                }
                else
                {
                    cout<<"1";
                    b--;
                    x--;
                    c=0;
                }
            }
        }
    }
}
